
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 37;
  public static final int DOSPUNTOS = 35;
  public static final int GET_MOVES_COUNT = 49;
  public static final int RANDOM = 53;
  public static final int WITH = 12;
  public static final int MUTUAL = 42;
  public static final int REWARD = 44;
  public static final int DIFERENTE = 22;
  public static final int SCORING = 10;
  public static final int LLAVEDER = 29;
  public static final int DEFECTION = 43;
  public static final int MATCH = 3;
  public static final int RULES = 6;
  public static final int IDENTIFICADOR = 41;
  public static final int NOT = 27;
  public static final int MENORIGUAL = 19;
  public static final int AND = 25;
  public static final int GET_LAST_N_MOVES = 50;
  public static final int IGUAL = 21;
  public static final int CORDER = 31;
  public static final int OR = 26;
  public static final int STRATEGIES = 8;
  public static final int MAIN = 4;
  public static final int IF = 15;
  public static final int PARENTESISIZQ = 32;
  public static final int MAYORIGUAL = 20;
  public static final int INITIAL = 5;
  public static final int DECIMAL = 38;
  public static final int EOF = 0;
  public static final int ROUNDS = 9;
  public static final int PUNISHMENT = 45;
  public static final int error = 1;
  public static final int COMA = 34;
  public static final int CADENA = 40;
  public static final int PLAYERS = 7;
  public static final int TOTAL_ROUNDS = 56;
  public static final int MENOR = 23;
  public static final int BETRAYAL = 46;
  public static final int STRATEGY = 2;
  public static final int ASIGNACION = 18;
  public static final int MAYOR = 24;
  public static final int SELF_HISTORY = 55;
  public static final int ROUND_NUMBER = 48;
  public static final int LAST_MOVE = 52;
  public static final int COOPERATION = 47;
  public static final int ELSE = 17;
  public static final int PUNTO = 36;
  public static final int GET_MOVE = 51;
  public static final int HISTORY = 57;
  public static final int LLAVEIZQ = 28;
  public static final int THEN = 16;
  public static final int BOOLEANO = 39;
  public static final int SEED = 13;
  public static final int PARENTESISDER = 33;
  public static final int ACC = 14;
  public static final int OPPONENT_HISTORY = 54;
  public static final int CORIZQ = 30;
  public static final int RUN = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRATEGY",
  "MATCH",
  "MAIN",
  "INITIAL",
  "RULES",
  "PLAYERS",
  "STRATEGIES",
  "ROUNDS",
  "SCORING",
  "RUN",
  "WITH",
  "SEED",
  "ACC",
  "IF",
  "THEN",
  "ELSE",
  "ASIGNACION",
  "MENORIGUAL",
  "MAYORIGUAL",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "AND",
  "OR",
  "NOT",
  "LLAVEIZQ",
  "LLAVEDER",
  "CORIZQ",
  "CORDER",
  "PARENTESISIZQ",
  "PARENTESISDER",
  "COMA",
  "DOSPUNTOS",
  "PUNTO",
  "NUMERO",
  "DECIMAL",
  "BOOLEANO",
  "CADENA",
  "IDENTIFICADOR",
  "MUTUAL",
  "DEFECTION",
  "REWARD",
  "PUNISHMENT",
  "BETRAYAL",
  "COOPERATION",
  "ROUND_NUMBER",
  "GET_MOVES_COUNT",
  "GET_LAST_N_MOVES",
  "GET_MOVE",
  "LAST_MOVE",
  "RANDOM",
  "OPPONENT_HISTORY",
  "SELF_HISTORY",
  "TOTAL_ROUNDS",
  "HISTORY"
  };
}

